[package]
name = "comic_sort"
version = "1.5.0"
authors = ["Ondřej Vágner <ondrej.vagner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shellexpand = "2.0"
regex = "1.3"
chrono = "0.4"
app_dirs2 = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
glob = "0.3"